### ISSUE TITLE
绑定KV命名空间的时候无法修改内容

### ISSUE THREAD

**Issue by black-zero358** [M3chD09/Cloudflare-Workers-E5Renew#3]
![image](https://user-images.githubusercontent.com/53086059/230752504-93fa828f-ad84-4058-9d81-c465dc2ca71c.png)

只能在后面选择。。

**Comment by cworld1** [comment]
一开始KV创建是啥就叫啥。如图我创建的KV叫microsoft-e5，那我就填写Token=microsoft-e5。

![image](https://user-images.githubusercontent.com/37377181/230773727-c12f064f-d3af-446c-b2af-e893975882d3.png)
